language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: zm5nxmFmsz6Eh0KWd2Dx8w+YtbmWL75P8xa7pglxEGBQlktFdi0w9Sx7BSAyvXTfg5IDuABS3TYc6rlQhMIv4bL13V0Pz0IglsK1/62bOEcP0VY3GXY8qic7uODqq5broiHgZWLSVlD7hNZtdr6FwJMnDEM92Znix2OB5Mz38ciAPYHenQCP0gSgjFyk0BRIZk3nFaOJj2e2oDmQg2hqcuuwoXEUgQh010I2xja8k3xRsjz/GCi7SaLrrtv9GRYEMp6rluCBy1xo8qbmuvPnaR0SY9S0y2dkCSHWf71OI2eJLnu/5IcnbRZGRXg5rncAhuF1Y57V09vEgz/FeDgCXxJDCxWl1E5h7Y4z5aMvLVFuRYvTE9wiun3oYszl7DWlpQEajACO8IMudnnaLT3VVe9XXZO5vZvXhqnSCuekMX/nDvPMndzznSV+lqqjFACEswKuCYKTInt6oV3/3evRA0AbhCkrkOtb6qpU/+YqRlGL1Q+Ko6i+FKqL4EM/jvMtZgsNg1x1MAtdA594NxSoGK3JUwqPyVnUx85Hx11oojEhTHjTXa6fn/TS2pDSpviHcXM+Pasi0ZMprd37TaFzwFilEQaEuHZE9ikJgOI3KLdWVyDKw0p3o56bAbriuHs/qDLBxkOnhmI+tPAIGX56Pn6Ch74Rcz+2hN5kg6p2DTc=
  app: floating-castle-85065
  on:
    repo: daxapps/WebDevQnAs
