language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: bfk52RAC1LJmt11nvnUCgCF4uMY/oOz3p3eoWllFZfkDiRvbTx19CbsEpTDES2SNF8k3asKYVLXyw2rGYEn+y2gArMKjyFmUHspgxpgzVY0zT/dChOmxzYywTH4p5nXsWJW8E5n+fnygTYk3QIu4FGm245OemqmVr0suBqTCICdI0M5VmYd1iH59D3U0qr3lu+wjnaKT0rBHkjZUeXiQQySqfAfk/LyFtq3XpulVMDq/GYqzHE2LmN/aIKZyi0c4Yzu7WdQn/FqG9vWr2UuZz1AnqduaMTGJInROBGoek9rEf1Q0JYU/zLvDy9RuZHaUFJc3xovMS2W/Wzq/ci6bmfCGa8NHPsRWMTo4+uyG3u/4GZAzPjlspKcJNKWX8EIgE/ohEHWvUwX7/ejoJx6r6MziKU7RS87ZGtP5jmtL5AWSOE4FtAdNaTxlNRN1qQqwyaEYR5f6RGz26RWsWscfnNhkuT2176QcY087BdPy41hw5gKhWKQBS0IupU6hxPpdqcYZBY+vn5k/xDxNwsyguIx8rxxI5sGaIGtHhizExpcsK0S9VhW2eXTvolXq7N09bh47srGRzMUZ08sUzItAp2dTOIcN1q+yFYcLl3f8mTYTvp2Vq8O94jeLlZ3TMWAYPA4vLxaBlCuD4L26iBDtd+ub+DqjndlR3UnDfMtTa7M=
  app: webdevqnas
  on:
    repo: daxapps/WebDevQnAs
